---
env:
  es6: true
  node: true
plugins:
  - "sort-class-members"
  - "jsdoc"
  - "@stylistic"
  - "@typescript-eslint"
extends:
- "eslint:recommended"
- "plugin:@stylistic/disable-legacy"
globals:
  BigInt: true
  window: true
parserOptions:
  ecmaVersion: 2020
settings:
  jsdoc:
    preferredTypes:
      boolean: Boolean
      number: Number
      bigint: BigInt
      string: String
      object: Object
    tagNamePreference:
      param: arg
      argument: arg
      property: prop
      augments: extends
rules:
  "@stylistic/array-bracket-spacing":
    - 2
    - never
  "@stylistic/arrow-parens": 2
  "@typescript-eslint/ban-ts-comment":
  - 2
  - ts-expect-error: allow-with-description
    ts-ignore: allow-with-description
  "@stylistic/brace-style":
  - 2
  - 1tbs
  - allowSingleLine: false
  "@stylistic/comma-dangle":
  - 2
  - never
  "@typescript-eslint/consistent-type-definitions": 2
  "curly": 2
  "@stylistic/eol-last":
  - 2
  - always
  "@stylistic/indent":
  - 2
  - 4
  - SwitchCase: 1
    ignoreComments: false
  "@stylistic/keyword-spacing":
  - 2
  - after: true
    overrides:
      catch:
        after: false
      for:
        after: false
      if:
        after: false
      switch:
        after: false
      while:
        after: false
  "@stylistic/member-delimiter-style": 2
  "@stylistic/no-explicit-any": 0
  "@stylistic/no-multi-spaces":
  - 2
  - exceptions:
      VariableDeclarator: true
  "@stylistic/no-multiple-empty-lines":
  - 2
  - max: 1
  "no-prototype-builtins": 0
  "@stylistic/no-trailing-spaces": 2
  "no-var": 2
  "@stylistic/object-curly-spacing":
  - 2
  - never
  "object-shorthand":
  - 2
  - consistent-as-needed
  "prefer-const": 2
  "@stylistic/quotes":
  - 2
  - double
  "require-atomic-updates": 1
  "@stylistic/semi":
  - 2
  - always
  sort-class-members/sort-class-members:
  - 2
  - order:
    - "[alphabetical-properties]"
    - constructor
    - update
    - "[alphabetical-getters]"
    - "[alphabetical-methods]"
    - "[alphabetical-conventional-private-methods]"
    - "on"
    - "[alphabetical-static-properties]"
    - "[alphabetical-static-methods]"
    - "[everything-else]"
    - "[custom-inspect-method]"
    - toString
    - toJSON
    groups:
      alphabetical-static-properties:
      - type: property
        sort: alphabetical
        static: true
      alphabetical-static-methods:
      - type: method
        sort: alphabetical
        static: true
      alphabetical-getters:
      - kind: get
        sort: alphabetical
      alphabetical-properties:
      - type: property
        sort: alphabetical
        static: false
      alphabetical-methods:
      - type: method
        sort: alphabetical
      alphabetical-conventional-private-methods:
      - name: "/_.+/"
        type: method
        sort: alphabetical
      custom-inspect-method:
      - name: "[util.inspect.custom]"
        type: method
  "@stylistic/space-infix-ops": 2
  jsdoc/check-types:
    - 2
  jsdoc/check-tag-names:
    - 2
  jsdoc/check-alignment:
    - 2
overrides:
- files:
  - "*.ts"
  rules:
    "@stylistic/indent":
    - 2
    - 2
    - SwitchCase: 1
      ignoreComments: false
    "@stylistic/object-curly-spacing":
    - 2
    - always
    "@stylistic/key-spacing":
    - 2
    - align: value
    "@typescript-eslint/no-explicit-any": 0
  parserOptions:
    sourceType: module
  parser: "@typescript-eslint/parser"
  extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@stylistic/disable-legacy
