env:
  es6: true
  node: true
extends: "eslint:recommended"
globals:
  window: true
parserOptions:
  ecmaVersion: 2017
rules:
  no-var: 2
  prefer-const: 2
  semi: [2, "always"]
  require-atomic-updates: 1
  no-prototype-builtins: 0
  no-trailing-spaces: 2
  keyword-spacing: [2, {
    "after": true,
    "overrides": {
      "if": { "after": false },
      "for": { "after": false },
      "while": { "after": false },
      "catch": { "after": false },
      "switch": { "after": false }
    }
  }]
  brace-style: [2, "1tbs", { "allowSingleLine": false }]